package com.example.flightreservationsystem.models;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Builder
@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "Reservation-Info")
public class ReservationDynamoModel {
    @DynamoDBAttribute
    private boolean cancelled;
    @DynamoDBAttribute
    private String flightNumber;
    @DynamoDBAttribute
    private String email;
    @DynamoDBAutoGeneratedKey
    @DynamoDBHashKey
    private String pnrNo;
    @DynamoDBAttribute
    private String phoneNumber;
    @DynamoDBAttribute
    private String firstName;
    @DynamoDBAttribute
    private String lastName;
    @DynamoDBAttribute
    private String to;
    @DynamoDBAttribute
    private String from;
    @DynamoDBAttribute
    private String departTime;
    @DynamoDBAttribute
    private String arrivalTime;
    @DynamoDBAttribute
    private String travelDate;
    @DynamoDBAttribute
    private String bookingDate;
}